packageExtensions:
  "@walletconnect/modal-ui@*":
    dependencies:
      lit-html: "*"
  "@wagmi/core@*":
    dependencies:
      "@tanstack/query-core": "*"
      "@tanstack/react-query": "*"
  "wagmi@*":
    dependencies:
      "@tanstack/react-query": "*"
