/**
 * Asset List for Preloading
 * 
 * This file is auto-generated by the updateAssetList.js script.
 * Do not edit this file directly.
 */

// List of assets to preload
const assetList = {
  images: [
    // Global assets
    '/acylprivylogo.png',
    '/acylprivylogo.webp',
    '/bighomepagelogo.png',
    '/bighomepagelogo.webp',
    '/circleheaderlogo.png',
    '/circleheaderlogo.webp',
    '/homepagebg.png',
    '/homepagebg.webp',
    '/ppheaderlogo.png',
    '/ppheaderlogo.webp',

    // Contribute assets
    '/images/contribute/freemember.png',
    '/images/contribute/freemember.webp',
    '/images/contribute/paidmember.png',
    '/images/contribute/paidmember.webp',

    // Digitaldaydream assets
    '/images/digitaldaydream/ddbg.png',
    '/images/digitaldaydream/ddbg.webp',
    '/images/digitaldaydream/ddtitle.png',
    '/images/digitaldaydream/ddtitle.webp',
    '/images/digitaldaydream/ddwithtext.png',
    '/images/digitaldaydream/ddwithtext.webp',

    // Discover assets
    '/images/discover/discoverbg.png',
    '/images/discover/discoverbg.webp',
    '/images/discover/groupthinklove.png',
    '/images/discover/groupthinklove.webp',
    '/images/discover/ifoundit.png',
    '/images/discover/ifoundit.webp',
    '/images/discover/iso.png',
    '/images/discover/iso.webp',
    '/images/discover/salem.png',
    '/images/discover/salem.webp',

    // Film assets
    '/images/film/ddposter.png',
    '/images/film/ddposter.webp',
    '/images/film/ddwithtext.png',
    '/images/film/ddwithtext.webp',
    '/images/film/filmbg.png',
    '/images/film/filmbg.webp',
    '/images/film/gtlposter.png',
    '/images/film/gtlposter.webp',
    '/images/film/gtlwithtext.png',
    '/images/film/gtlwithtext.webp',
    '/images/film/ifiposter.png',
    '/images/film/ifiposter.webp',
    '/images/film/ifiwithtext.png',
    '/images/film/ifiwithtext.webp',
    '/images/film/isoposter.png',
    '/images/film/isoposter.webp',
    '/images/film/isowithtext.png',
    '/images/film/isowithtext.webp',

    // Groupthinklove assets
    '/images/groupthinklove/gtlbg.png',
    '/images/groupthinklove/gtlbg.webp',
    '/images/groupthinklove/gtllogo.png',
    '/images/groupthinklove/gtllogo.webp',
    '/images/groupthinklove/gtlwithtext.png',
    '/images/groupthinklove/gtlwithtext.webp',

    // Ifoundit assets
    '/images/ifoundit/ifibg.png',
    '/images/ifoundit/ifibg.webp',
    '/images/ifoundit/ifilogo.png',
    '/images/ifoundit/ifilogo.webp',
    '/images/ifoundit/ifiwithtext.png',
    '/images/ifoundit/ifiwithtext.webp',

    // Isolation assets
    '/images/isolation/isobg.png',
    '/images/isolation/isobg.webp',
    '/images/isolation/isotitle.png',
    '/images/isolation/isotitle.webp',
    '/images/isolation/isowithtext.png',
    '/images/isolation/isowithtext.webp',
    '/images/isolation/meditatetext.png',
    '/images/isolation/meditatetext.webp',
    '/images/isolation/prisoner.png',
    '/images/isolation/prisoner.webp',

    // Podplayr assets
    '/images/podplayr/pptextlogo.png',
    '/images/podplayr/pptextlogo.webp',

    // Radio assets
    '/images/radio/radiobg.png',
    '/images/radio/radiobg.webp',
    '/images/radio/radiologo.png',
    '/images/radio/radiologo.webp',

    // Salemtries assets
    '/images/salemtries/salemlogo.png',
    '/images/salemtries/salemlogo.webp',
    '/images/salemtries/salemstream.png',
    '/images/salemtries/salemstream.webp',
    '/images/salemtries/salemtriesbg.png',
    '/images/salemtries/salemtriesbg.webp',

    // Sazon assets
    '/images/sazon/swsbanner.png',
    '/images/sazon/swsbanner.webp',
    '/images/sazon/swsbg.png',
    '/images/sazon/swsbg.webp',
    '/images/sazon/swslogo.png',
    '/images/sazon/swslogo.webp',
    '/images/sazon/swsstream.png',
    '/images/sazon/swsstream.webp',

    // Stream assets
    '/images/stream/salemstream.png',
    '/images/stream/salemstream.webp',
    '/images/stream/streambg.png',
    '/images/stream/streambg.webp',
    '/images/stream/swsstream.png',
    '/images/stream/swsstream.webp',

    // Tv assets
    '/images/tv/afuerafont.png',
    '/images/tv/afuerafont.webp',
    '/images/tv/tvbg.png',
    '/images/tv/tvbg.webp',
  ],
  videos: [
    // Digitaldaydream videos
    '/images/digitaldaydream/ddsequence.mp4',

    // Groupthinklove videos
    '/images/groupthinklove/gtltrailer1.mp4',
    '/images/groupthinklove/gtltrailer2.mp4',
    '/images/groupthinklove/gtltrailer3.mp4',

    // Ifoundit videos
    '/images/ifoundit/ifisequence1.mp4',

    // Isolation videos
    '/images/isolation/isotrailer.mp4',

    // Podplayr videos
    '/images/podplayr/ppintrovideo.mp4',
    '/images/podplayr/privylogin.mp4',

    // Salemtries videos
    '/images/salemtries/salemsequence1.mp4',

    // Sazon videos
    '/images/sazon/swstrailer1.mp4',
  ],
  gifs: [
    // Radio GIFs
    '/images/radio/latasha.gif',
    '/images/radio/sazon.gif',
    '/images/radio/will.gif',

    // Salemtries GIFs
    '/images/salemtries/salemtries.gif',
  ]
};

export default assetList;
