/**
 * Asset List for Preloading
 * 
 * This file is auto-generated by the updateAssetList.js script.
 * Do not edit this file directly.
 */

// List of assets to preload
const assetList = {
  images: [
    // Global assets
    '/acylprivylogo.webp',
    '/bighomepagelogo.webp',
    '/circleheaderlogo.webp',
    '/homepagebg.webp',
    '/ppheaderlogo.webp',

    // Brushstrokes assets
    '/images/brushstrokes/bsmobile1.webp',
    '/images/brushstrokes/bsmobile2.webp',
    '/images/brushstrokes/bspagebg.webp',
    '/images/brushstrokes/bstrokepagebg.webp',
    '/images/brushstrokes/bstrokes.webp',

    // Caf assets
    '/images/caf/cafbg.webp',
    '/images/caf/cafmobile1.webp',
    '/images/caf/cafmobile2.webp',
    '/images/caf/cafthumbnail.webp',

    // Contribute assets
    '/images/contribute/freemember.webp',
    '/images/contribute/paidmember.webp',

    // Cyberjam assets
    '/images/cyberjam/cjmobile1.webp',
    '/images/cyberjam/cjmobile2.webp',
    '/images/cyberjam/cyberjam.webp',
    '/images/cyberjam/cyberpagebg.webp',

    // Decentralympics assets
    '/images/decentralympics/decentmobile1.webp',
    '/images/decentralympics/decentmobile2.webp',
    '/images/decentralympics/decentrapagebg.webp',
    '/images/decentralympics/decetra.webp',

    // Digitaldaydream assets
    '/images/digitaldaydream/ddbg.webp',
    '/images/digitaldaydream/ddmobile1.webp',
    '/images/digitaldaydream/ddmobile2.webp',
    '/images/digitaldaydream/ddtitle.webp',
    '/images/digitaldaydream/ddwithtext.webp',

    // Discover assets
    '/images/discover/discoverbg.webp',
    '/images/discover/groupthinklove.webp',
    '/images/discover/ifoundit.webp',
    '/images/discover/iso.webp',
    '/images/discover/salem.webp',

    // Events assets
    '/images/events/eventpagebg.webp',

    // Experimental assets
    '/images/experimental/experpagebg.webp',
    '/images/experimental/nycmobile1.webp',
    '/images/experimental/nycmobile2.webp',
    '/images/experimental/nyevent.webp',

    // Film assets
    '/images/film/ddposter.webp',
    '/images/film/ddwithtext.webp',
    '/images/film/filmbg.webp',
    '/images/film/gtlposter.webp',
    '/images/film/gtlwithtext.webp',
    '/images/film/ifiposter.webp',
    '/images/film/ifiwithtext.webp',
    '/images/film/isoposter.webp',
    '/images/film/isowithtext.webp',

    // Groupthinklove assets
    '/images/groupthinklove/gtlbg.webp',
    '/images/groupthinklove/gtllogo.webp',
    '/images/groupthinklove/gtlmobile1.webp',
    '/images/groupthinklove/gtlmobile2.webp',
    '/images/groupthinklove/gtlwithtext.webp',

    // Ifoundit assets
    '/images/ifoundit/ifibg.webp',
    '/images/ifoundit/ifilogo.webp',
    '/images/ifoundit/ifimobile1.webp',
    '/images/ifoundit/ifimobile2.webp',
    '/images/ifoundit/ifiwithtext.webp',

    // Isolation assets
    '/images/isolation/isobg.webp',
    '/images/isolation/isomobile1.webp',
    '/images/isolation/isotitle.webp',
    '/images/isolation/isowithtext.webp',
    '/images/isolation/meditatetext.webp',
    '/images/isolation/prisoner.webp',

    // Podplayr assets
    '/images/podplayr/ppmobile1.webp',
    '/images/podplayr/ppmobile2.webp',
    '/images/podplayr/pptextlogo.webp',

    // Radio assets
    '/images/radio/radiobg.webp',
    '/images/radio/radiologo.webp',

    // Reelcolors assets
    '/images/reelcolors/rcthumbnail.webp',
    '/images/reelcolors/reelcoloursbg.webp',

    // Salemtries assets
    '/images/salemtries/salemlogo.webp',
    '/images/salemtries/salemstream.webp',
    '/images/salemtries/salemtriesbg.webp',

    // Sazon assets
    '/images/sazon/swsbanner.webp',
    '/images/sazon/swsbg.webp',
    '/images/sazon/swslogo.webp',
    '/images/sazon/swsstream.webp',

    // Stream assets
    '/images/stream/salemstream.webp',
    '/images/stream/streambg.webp',
    '/images/stream/swsstream.webp',

    // Tv assets
    '/images/tv/afuerafont.webp',
    '/images/tv/tvbg.webp',
  ],
  videos: [
    // Brushstrokes videos
    '/images/brushstrokes/2025 ACYL LIVE BROOKLYN MEETUPO.mp4',

    // Caf videos
    '/images/caf/CTRL ALT FILM EVENT RECAP VIDEO.mp4',

    // Cyberjam videos
    '/images/cyberjam/2025 CYBERJAM 2024.mp4',

    // Decentralympics videos
    '/images/decentralympics/2025 DECENTRALYMPICS SEGMENT.mp4',

    // Digitaldaydream videos
    '/images/digitaldaydream/ddsequence.mp4',

    // Experimental videos
    '/images/experimental/2025 ACYL LIVE SCREENING.mp4',

    // Groupthinklove videos
    '/images/groupthinklove/gtltrailer1.mp4',
    '/images/groupthinklove/gtltrailer2.mp4',
    '/images/groupthinklove/gtltrailer3.mp4',

    // Ifoundit videos
    '/images/ifoundit/ifisequence1.mp4',

    // Isolation videos
    '/images/isolation/isotrailer.mp4',

    // Podplayr videos
    '/images/podplayr/ppintrovideo.mp4',
    '/images/podplayr/privylogin.mp4',

    // Salemtries videos
    '/images/salemtries/salemsequence1.mp4',

    // Sazon videos
    '/images/sazon/swstrailer1.mp4',
  ],
  gifs: [
    // Radio GIFs
    '/images/radio/latasha.gif',
    '/images/radio/sazon.gif',
    '/images/radio/will.gif',

    // Salemtries GIFs
    '/images/salemtries/salemtries.gif',
  ]
};

export default assetList;
